name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    # =========================
    # SMOKE (PR)
    # =========================
    - name: Run smoke tests
      if: github.event_name == 'pull_request'
      run: |
        pytest -m smoke -n auto --dist=loadscope \
        --reruns 2 --reruns-delay 1 \
        --alluredir=allure-results -q

    # =========================
    # FULL REGRESSION (MAIN)
    # =========================
    - name: Run full regression
      if: github.ref == 'refs/heads/main'
      run: |
        pytest -m "not flaky" -n auto --dist=loadscope \
        --reruns 2 --reruns-delay 1 \
        --alluredir=allure-results -q

    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results